export type ListingSummary = {
  id: string;
  referenceCode: string;
  title: string;
  memberEntityName: string;
  propertyTypeName: string;
  propertySubtypeName: string | null;
  purposeName: string;
  provinceName: string;
  districtName: string;
  municipalityName: string;
  price: number;
  currencyCode: string;
  isPriceNegotiable: boolean;
  landArea: number;
  areaUnitName: string;
  measurementSystem: string;
  areaInSquareFeet: number;
  bedrooms: number | null;
  bathrooms: number | null;
  status: string;
  networkVisibility: string;
  isPublicVisible: boolean;
  primaryImageUrl: string | null;
  createdAt: string;
};

export type ListingSearchResult = { items: ListingSummary[]; totalCount: number; page: number; pageSize: number };

export type ListingMedia = { id: string; url: string; isPrimary: boolean; sortOrder: number; caption: string | null };
export type ListingDocument = { id: string; documentType: string | null; createdAt: string };

export type ListingDetail = {
  id: string;
  referenceCode: string;
  memberEntityId: string;
  memberEntityName: string;
  title: string;
  description: string | null;
  internalNotes: string | null;
  propertyTypeId: string;
  propertyTypeName: string;
  propertySubtypeId: string | null;
  propertySubtypeName: string | null;
  purposeId: string;
  purposeName: string;
  provinceId: string;
  provinceName: string;
  districtId: string;
  districtName: string;
  municipalityId: string;
  municipalityName: string;
  wardId: string;
  wardNumber: number;
  localityId: string | null;
  localityName: string | null;
  landmark: string | null;
  latitude: number | null;
  longitude: number | null;
  currencyId: string;
  currencyCode: string;
  price: number;
  isPriceNegotiable: boolean;
  landArea: number;
  builtUpArea: number | null;
  areaUnitId: string;
  areaUnitName: string;
  measurementSystem: string;
  ropaniValue: number | null;
  aanaValue: number | null;
  paisaValue: number | null;
  damValue: number | null;
  bighaValue: number | null;
  katthaValue: number | null;
  dhurValue: number | null;
  areaInSquareFeet: number;
  hasRoadAccess: boolean;
  roadWidthFeet: number | null;
  roadType: string | null;
  facing: string | null;
  bedrooms: number | null;
  bathrooms: number | null;
  floors: number | null;
  parkingSpaces: number | null;
  furnishing: string | null;
  networkVisibility: string;
  isPublicVisible: boolean;
  status: string;
  rejectionReason: string | null;
  expiresAt: string | null;
  createdAt: string;
  updatedAt: string | null;
  isOwner: boolean;
  amenityNames: string[];
  amenityIds: string[];
  media: ListingMedia[];
  documents: ListingDocument[];
};

export type ListingContact = { contactName: string | null; phone: string | null; email: string | null };

export type NamedRef = { id: string; name: string };
export type PropertyTypeWithSubtypes = { id: string; name: string; subtypes: NamedRef[] };
export type WardRef = { id: string; number: number };
export type AreaUnitRef = { id: string; name: string; abbreviation: string | null };
export type CurrencyRef = { id: string; code: string; symbol: string };

export type PublicPropertySummary = {
  id: string;
  referenceCode: string;
  title: string;
  memberEntityName: string;
  propertyTypeName: string;
  purposeName: string;
  provinceName: string;
  districtName: string;
  municipalityName: string;
  price: number;
  currencyCode: string;
  landArea: number;
  areaUnitName: string;
  bedrooms: number | null;
  bathrooms: number | null;
  primaryImageUrl: string | null;
};

export type PublicPropertySearchResult = { enabled: boolean; items: PublicPropertySummary[]; totalCount: number; page: number; pageSize: number };

export type PublicPropertyDetail = {
  id: string;
  referenceCode: string;
  title: string;
  description: string | null;
  memberEntityName: string;
  propertyTypeName: string;
  propertySubtypeName: string | null;
  purposeName: string;
  provinceName: string;
  districtName: string;
  municipalityName: string;
  wardNumber: number;
  localityName: string | null;
  landmark: string | null;
  price: number;
  currencyCode: string;
  isPriceNegotiable: boolean;
  landArea: number;
  builtUpArea: number | null;
  areaUnitName: string;
  measurementSystem: string;
  ropaniValue: number | null;
  aanaValue: number | null;
  paisaValue: number | null;
  damValue: number | null;
  bighaValue: number | null;
  katthaValue: number | null;
  dhurValue: number | null;
  hasRoadAccess: boolean;
  roadWidthFeet: number | null;
  facing: string | null;
  bedrooms: number | null;
  bathrooms: number | null;
  floors: number | null;
  parkingSpaces: number | null;
  furnishing: string | null;
  amenityNames: string[];
  mediaUrls: string[];
  createdAt: string;
};

// Mirrors REAK.Api's LandAreaInput (spec §11) — only the field set matching measurementSystem
// is meaningful. No areaUnitId: the server derives it from measurementSystem.
export type LandAreaRequestInput = {
  measurementSystem: number;
  ropaniValue?: number;
  aanaValue?: number;
  paisaValue?: number;
  damValue?: number;
  bighaValue?: number;
  katthaValue?: number;
  dhurValue?: number;
  landArea?: number;
};

export type CreateListingInput = {
  title: string;
  description?: string;
  propertyTypeId: string;
  propertySubtypeId?: string;
  purposeId: string;
  provinceId: string;
  districtId: string;
  municipalityId: string;
  wardId: string;
  localityId?: string;
  landmark?: string;
  latitude?: number;
  longitude?: number;
  currencyId: string;
  price: number;
  isPriceNegotiable: boolean;
  landArea: LandAreaRequestInput;
  builtUpArea?: number;
  hasRoadAccess: boolean;
  roadWidthFeet?: number;
  roadType?: string;
  facing?: string;
  bedrooms?: number;
  bathrooms?: number;
  floors?: number;
  parkingSpaces?: number;
  furnishing?: string;
  internalNotes?: string;
  amenityIds?: string[];
  contact?: ListingContact;
  expiresAt?: string;
};

export type UpdateListingInput = Omit<CreateListingInput, "amenityIds" | "contact">;
